In [1]:
#math module

#Square root and Power

import math
print("Square root of 49:", math.sqrt(49))

print("2 raised to the power 3:", math.pow(2, 3))

Square root of 49: 7.0
2 raised to the power 3: 8.0


In [2]:
#using ceil and floor

print("Ceiling of 7.1:", math.ceil(7.1))
print("Floor of 7.9:", math.floor(7.9))

Ceiling of 7.1: 8
Floor of 7.9: 7


In [3]:
#value of π (pi) and e from the math module.

print("Value of pi:", math.pi)
print("Value of e:", math.e)

Value of pi: 3.141592653589793
Value of e: 2.718281828459045


In [4]:
#the area of a circle with radius = 5.

radius = 5
area = math.pi * math.pow(radius, 2)
print("Area of circle:", area)

Area of circle: 78.53981633974483


In [5]:
# Trigonometric Functions (in radians)

print("sin(pi/2):", math.sin(math.pi/2))   
print("cos(0):", math.cos(0))             
print("tan(pi/4):", math.tan(math.pi/4))  #tan(pi/4)=?

sin(pi/2): 1.0
cos(0): 1.0
tan(pi/4): 0.9999999999999999


In [6]:
# random

#generate 5 random floats between 0 and 1
import random

for i in range(5):
    print(random.random())

#Generate a random number between 1 and 100.

num = random.randint(1, 100)
print("Random integer:", num)

0.8853057379040938
0.38621824078768263
0.4623965489378744
0.26915177081682673
0.23530540482227735
Random integer: 82


In [7]:
#to select a random fruit from a list.

friends = ["Anu", "Rahul", "Meera", "Arjun", "Namitha"]
print("Chosen friend:", random.choice(friends))

#shuffle the order of students in a list.

students = ["Anu", "Rahul", "Meera", "Arjun", "Namitha"]
random.shuffle(students)
print("Shuffled students:", students)


Chosen friend: Namitha
Shuffled students: ['Anu', 'Rahul', 'Namitha', 'Arjun', 'Meera']


In [8]:
#a lottery ticket of 6 unique numbers between 1 and 49 using random.sample().

lottery = random.sample(range(1, 50), 6)
print("Lottery numbers:", lottery)

#generate a random float
num = random.uniform(1.5, 6.5)
print("Random float:", num)


Lottery numbers: [22, 11, 34, 29, 21, 7]
Random float: 2.9306905357978117


In [9]:
#TASK 1

#program that simulates 100 coin tosses and counts how many times Heads appeared

heads = 0
for i in range(100):
    toss = random.choice(["Heads", "Tails"])
    if toss == "Heads":
        heads += 1

print("Heads appeared:", heads, "times")


Heads appeared: 46 times


In [10]:
#TASK 2

#Create a rock-paper-scissors game against the computer.

choices = ["rock", "paper", "scissors"]

user = input("Enter rock, paper, or scissors: ").lower()
comp = random.choice(choices)

print("You chose:", user)
print("Computer chose:", comp)

if user == comp:
    print("It's a tie!")
elif (user == "rock" and comp == "scissors") or \
     (user == "paper" and comp == "rock") or \
     (user == "scissors" and comp == "paper"):
    print("You win!")
else:
    print("Computer wins!")


Enter rock, paper, or scissors:  paper


You chose: paper
Computer chose: rock
You win!


In [11]:
# time-date

#only date
from datetime import date, timedelta

today = date.today()
tomorrow = today + timedelta(days=40)

print("Today:", today)
print("date:", tomorrow)


Today: 2025-08-25
date: 2025-10-04


In [12]:
#current date and time

from datetime import datetime
now = datetime.now()
print("Now:", now)   


from datetime import datetime, timedelta
tomorrow = now + timedelta(days=40)

print("Today:", now)
print("Tomorrow:", tomorrow)


Now: 2025-08-25 20:34:11.486757
Today: 2025-08-25 20:34:11.486757
Tomorrow: 2025-10-04 20:34:11.486757


In [13]:
#fnding difference between two dates

from datetime import date
today = date.today()

new_year = date(2026, 1, 1)
x = new_year - today
print("Days until New Year:", x.days)

Days until New Year: 129


In [14]:
#Specified date and time
from datetime import datetime, timedelta

# Create a specified date and time → (year, month, day, hour, minute, second)
specified_datetime = datetime(2025, 8, 16, 14, 30, 0)  # 16 Aug 2025, 2:30 PM

# Add 1 day
tomorrow = specified_datetime + timedelta(days=40)

# Add 2 hours
later_time = specified_datetime + timedelta(hours=2)

print("Specified Date & Time:", specified_datetime)
print("Tomorrow (same time):", tomorrow)
print("After 2 hours:", later_time)

Specified Date & Time: 2025-08-16 14:30:00
Tomorrow (same time): 2025-09-25 14:30:00
After 2 hours: 2025-08-16 16:30:00


In [15]:
#numpy

#pip install numpy
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)

# Create a 2D array
array_2d = np.array([[1, 2], [3, 4]])
print("2D Array:\n", array_2d)                    #2 dimenional array * 1dimenio =?

# Perform array addition                          #2*2 * 2*1 =
result = array_1d + 2
print("Array Addition:", result)

# Compute the dot product of two arrays
dot_product = np.dot(array_2d, [[1], [1]])       #
print("Dot Product:\n", dot_product) #  1*1+2*1=1+2=3

1D Array: [1 2 3 4]
2D Array:
 [[1 2]
 [3 4]]
Array Addition: [3 4 5 6]
Dot Product:
 [[3]
 [7]]


In [16]:
# lists or tuples into NumPy arrays using np.array()
import numpy as np

# From a list
array_from_list = np.array([1, 2, 3, 4])
print(array_from_list)

# From a tuple
array_from_tuple = np.array((5, 6, 7))
print(array_from_tuple)

[1 2 3 4]
[5 6 7]


In [17]:
#Using Built-in Functions
#Zeros and Ones

zeros_array = np.zeros((3, 3))  # 3x3 array of zeros
ones_array = np.ones((2, 4))   # 2x4 array of ones
zeros_array
ones_array

#Empty Array (uninitialized array (values are random)
empty_array = np.empty((2, 2))
empty_array

#full array
full_array = np.full((3, 3), 7)  
print(full_array)

#using range 

#(np.arange(start, stop, step)

range_array = np.arange(1, 10, 2)  
print(range_array)

linspace_array = np.linspace(0, 1, 5)  # equal division btw 0 & 1 into 5 parts
print(linspace_array)

# Random Arrays
random_integers = np.random.randint(0, 100, (3, 3))
print(random_integers)

#Identity and Diagonal Matrice
#4=n (n*n matrix)

identity_matrix = np.eye(4)   
print(identity_matrix)

diagonal_matrix = np.diag([5, 2, 3])
print(diagonal_matrix)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[[69 73 22]
 [ 6 23 54]
 [97 85 57]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[5 0 0]
 [0 2 0]
 [0 0 3]]


In [18]:
#Array Properties
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array Shape:", arr.shape)  # (2, 3) -> 2 rows, 3 columns
print("Array Size:", arr.size)    # Total number of elements (6)
print("Array Dimensions:", arr.ndim)  # Number of dimensions (2)
print("Data Type:", arr.dtype)    # Data type of elements (int64) #64bit

Array Shape: (2, 3)
Array Size: 6
Array Dimensions: 2
Data Type: int64


In [19]:
#Combining Arrays
import numpy as np

# Create two 3x3 arrays: one filled with zeros, the other with ones
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 3))
full = np.full((3,3),5)
combined_array = np.hstack((zeros_array, ones_array,full))
combined_array 

array([[0., 0., 0., 1., 1., 1., 5., 5., 5.],
       [0., 0., 0., 1., 1., 1., 5., 5., 5.],
       [0., 0., 0., 1., 1., 1., 5., 5., 5.]])

In [20]:
#Indexing:Access individual elements

arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Element at (0, 1):", arr[0, 1])

#Slicing:Extract a sub-array
# Extract first row
print("First Row:", arr[0, :])

# Extract first column
print("First Column:", arr[:, 0])

# Extract a 2x2 sub-array
print("Sub-array:\n", arr[0:2, 1:3])

#Reshaping Arrays:Change the dimensions of an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape((2, 3))
print("Reshaped Array:\n", reshaped)

#Boolean Indexing
# Boolean indexing to select elements greater than 25
selected_elements = arr[arr > 25]
print("Elements greater than 25:", selected_elements)

Element at (0, 1): 20
First Row: [10 20 30]
First Column: [10 40]
Sub-array:
 [[20 30]
 [50 60]]
Reshaped Array:
 [[1 2 3]
 [4 5 6]]
Elements greater than 25: []


In [21]:
selected_elements = arr[arr > 25]
print("Elements greater than 25:", selected_elements)

Elements greater than 25: []


In [22]:
#TASK  :Creating a Symmetric Matrix AATRANSPOSE
#Dividing by 2 ensures that the off-diagonal elements are symmetrized

import numpy as np

# Create a random 3x3 matrix
random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)

# Generate a symmetric matrix by averaging the original matrix and its transpose
symmetric_matrix = (random_matrix + random_matrix.T) / 2
print("Symmetric Matrix:\n", symmetric_matrix)

Random Matrix:
 [[0.64780535 0.7372501  0.89630808]
 [0.69823508 0.13102377 0.39477964]
 [0.34591218 0.6942067  0.94224105]]
Symmetric Matrix:
 [[0.64780535 0.71774259 0.62111013]
 [0.71774259 0.13102377 0.54449317]
 [0.62111013 0.54449317 0.94224105]]


In [23]:
random_matrix = np.random.randint(1, 20,(5,3))
print("Random Matrix:\n", random_matrix)

Random Matrix:
 [[13 11 13]
 [10  6  2]
 [11 13  1]
 [ 3 15 19]
 [16  9 13]]


In [2]:
#TASK 3:
import numpy as np

# Create a 2D array of shape (4, 5) with random integers between 0 and 100
random_array = np.random.randint(0, 100, size=(4, 5))

print("2D Array filled with random integers:")
print(random_array)

2D Array filled with random integers:
[[46 43 30  1 73]
 [97 95 96 41 59]
 [17 11 53 91 68]
 [ 8  0 51 94 17]]


In [25]:
#TASK 4:

import numpy as np

# Arrays A and B
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([1, 2])

# Matrix multiplication using broadcasting
result = A * B  # Broadcasting automatically scales B across rows of A
print("Matrix Multiplication Result:\n", result)

Matrix Multiplication Result:
 [[ 1  4]
 [ 3  8]
 [ 5 12]]


In [26]:
#SUBMATRIX

# Create a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

# Extract a 2x2 submatrix from the center
submatrix1 = arr_2d[1:3, ]
submatrix = arr_2d[1:3, 1:3]
print(submatrix)
print("Extracted Submatrix:\n", submatrix)
submatrix1

[[ 6  7]
 [10 11]]
Extracted Submatrix:
 [[ 6  7]
 [10 11]]


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(arr_2d)
# Extract a 2x2 submatrix from the center
submatrix1 = arr_2d[1:3,1:3]
print(submatrix1)         # [5 6 7 8][9 10 11 12] :rows     #[2      3
                                                            #     6    7
                                                             #   10    11
                                                              #  14    15]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 6  7]
 [10 11]]


In [28]:
# Reshaping a 1D Array into a 2D Array
# Create a 1D array with 12 elements
arr = np.arange(1, 13)

# Reshape the 1D array into a 2D array with 3 rows and 4 columns
reshaped_arr = arr.reshape(3, 4)

print("Original Array:", arr)
print("Reshaped Array (3x4):\n", reshaped_arr)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
#Addition, Subtraction, Multiplication, Division :array
# import numpy as np
# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Element-wise addition
add_result = arr1 + arr2

# Element-wise subtraction
sub_result = arr1 - arr2

# Element-wise multiplication
mul_result = arr1 * arr2

# Element-wise division
div_result = arr1 / arr2

print("Addition:", add_result)
print("Subtraction:", sub_result)
print("Multiplication:", mul_result)
print("Division:", div_result)

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [12]:
#Operations with Scalars:You can perform arithmetic operations between an array and a scalar (a single number).
# Scalar addition
print("Add 5 to each element:", arr1 + 5)  

# Scalar multiplication
print("Multiply each element by 2:", arr1 * 2)  

Add 5 to each element: [6 7 8 9]
Multiply each element by 2: [2 4 6 8]


In [13]:
#element-wise operation
# Exponentials and logarithms
arr = np.array([1, 2, 3])

print("Exponential:", np.exp(arr)) 
print("Natural Log:", np.log(arr))  

Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural Log: [0.         0.69314718 1.09861229]


In [14]:
#Element-wise Power and Square Root
arr = np.array([1, 4, 9, 16, 25])

# Element-wise square root
sqrt_result = np.sqrt(arr)

# Element-wise power (raise each element to the power of 2)
power_result = np.power(arr, 2) #math.pow(3,2)

print("Square Root:", sqrt_result)
print("Power (Squared):", power_result)

Square Root: [1. 2. 3. 4. 5.]
Power (Squared): [  1  16  81 256 625]


In [15]:
#Comparison Operations:Element-wise comparisons return Boolean arrays.

arr1 = np.array([10, 20, 30])
arr2 = np.array([15, 20, 25])

print("Greater than:", arr1 > arr2) 
print("Less than or equal:", arr1 <= arr2)  
print("Equality:", arr1 == arr2)

Greater than: [False False  True]
Less than or equal: [ True  True False]
Equality: [False  True False]


In [16]:
#Sum, Mean, Min, Max
arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
total_sum = np.sum(arr)

# Mean of all elements
mean_value = np.mean(arr)

# Minimum element
min_value = np.min(arr)

# Maximum element
max_value = np.max(arr)

print("Sum:", total_sum)
print("Mean:", mean_value)
print("Min:", min_value)
print("Max:", max_value)


Sum: 15
Mean: 3.0
Min: 1
Max: 5


In [36]:
#TASK 5

import numpy as np

# Create an array of 10 numbers
numbers = np.array([4, 8, 15, 16, 23, 42, 3, 7, 12, 9])

# Calculate the standard deviation
std_dev = np.std(numbers)

print("Array of numbers:", numbers)
print("Standard Deviation:", std_dev)

Array of numbers: [ 4  8 15 16 23 42  3  7 12  9]
Standard Deviation: 10.97679370308106


In [37]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

# Element-wise multiplication
result = array1 * array2

# Sum of the resulting array
result_sum = np.sum(result)

print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise Multiplication Result:", result)
print("Sum of Result:", result_sum)

Array 1: [1 2 3 4 5]
Array 2: [10 20 30 40 50]
Element-wise Multiplication Result: [ 10  40  90 160 250]
Sum of Result: 550


In [19]:
#DATA PREPROCESSING : 
#Handling Missing Data (Imputation)
# Create an array with missing values (NaN)
data = np.array([1.0, 2.0, np.nan, 50.0, 5.0])

# Replace NaN with the mean of the array
mean_value = np.nanmean(data) # np.mean(data)
data_cleaned = np.nan_to_num(data, nan=mean_value)

print("Original Data:", data)
print("Cleaned Data:", data_cleaned)

Original Data: [ 1.  2. nan 50.  5.]
Cleaned Data: [ 1.   2.  14.5 50.   5. ]


In [20]:
# STANDISATION: (Z-score)

data = np.array([10, 12, 11, 14, 13, 100, 15, 16])
mean = np.mean(data)
std_dev = np.std(data)
z_scores = (data - mean) / std_dev
z_scores

#Mean for Data Normalization(scaling it to a desired range.( when scaling data to the range [0, 1], the mean can be subtracted from the data, and the result is divided by the range of the data (max - min).)
data = np.array([10, 20, 30, 40, 50])
min_val = np.min(data)
max_val = np.max(data)
normalized_data = (data - min_val) / (max_val - min_val)
normalized_data 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
#if range changes
a = 10  
b = 20
scaled_data = a + ((data - min_val) * (b - a)) / (max_val - min_val)
scaled_data

array([10. , 12.5, 15. , 17.5, 20. ])

In [26]:
pip install pandas


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
